version: 2

sources:
  - name: ecommerce_source  # Logical source name
    schema: public  # Where raw_orders exists
    tables:
      - name: raw_orders  # Actual table name
        description: "Raw order data from the transactional system"
