version: 2

models:
  - name: analytics_orders
    description: "Aggregated order data combining ecommerce and test project datasets."
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      
      - name: customer_id
        tests:
          - not_null
      
      - name: test_project_id
      
      - name: some_metric
