version: 2

sources:
  - name: ecommerce_models
    schema: ecommerce_ecommerce_schema
    tables:
      - name: stg_orders
        
  - name: test_project_models
    schema: my_test_my_test
    tables:
      - name: my_first_dbt_model 